path_data='/storages/LDATA/BrainstormDB/tDCS_MEG_ASSR/data/';
fnames = dir('/storages/LDATA/BrainstormDB/tDCS_MEG_ASSR/data/Sub*');

for gg=1:8%length(fnames)
    [pathstr,name,ext] = fileparts(fnames(gg,1).name);
    display(name)
    runs_names = dir([path_data name '/TDCS*']);
    for hh=1:length(runs_names)
        [pathstr_run,run,ext_run] = fileparts(runs_names(hh,1).name);
        display (run)
        trial_names=rdir([path_data name '/' run '/data*.mat'], '', '/storages/LDATA/BrainstormDB/tDCS_MEG_ASSR/data');
        sFiles=cell(1,length(trial_names));
        for qq=1:length(trial_names)
            sFiles{1,qq}=(trial_names(qq,1).name);
        end
        sFiles_backup=sFiles;
        sFiles_new = bst_process('CallProcess', 'process_select_tag', sFiles, [], ...
            'tag',    'baseline', ...
            'search', 2, ...  % Search the file comments
            'select', 2);  % Select only the files without the tag
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        Common_operator_file=rdir([path_data name '/' run '/results_MN_MEG_KERNEL*.mat'], '', '/storages/LDATA/BrainstormDB/tDCS_MEG_ASSR/data');
        for qq=1:length(sFiles_new)
            sFiles_last{1,qq}=(['link|' Common_operator_file(1,1).name '|' sFiles_new(1,qq).FileName]);
        end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%         sFiles_TF = bst_process('CallProcess', 'process_timefreq', sFiles_last, [], ...
%     'clusters',  {}, ...
%     'scoutfunc', 1, ...  % Mean
%     'edit',      struct(...
%          'Comment',         'Source-35-45Hz', ...
%          'TimeBands',       [], ...
%          'Freqs',           [35, 35.2, 35.4, 35.6, 35.8, 36, 36.2, 36.4, 36.6, 36.8, 37, 37.2, 37.4, 37.6, 37.8, 38, 38.2, 38.4, 38.6, 38.8, 39, 39.2, 39.4, 39.6, 39.8, 40, 40.2, 40.4, 40.6, 40.8, 41, 41.2, 41.4, 41.6, 41.8, 42, 42.2, 42.4, 42.6, 42.8, 43, 43.2, 43.4, 43.6, 43.8, 44, 44.2, 44.4, 44.6, 44.8, 45], ...
%          'MorletFc',        40, ...
%          'MorletFwhmTc',    2, ...
%          'ClusterFuncTime', 'none', ...
%          'Measure',         'none', ...
%          'Output',          'all', ...
%          'RemoveEvoked',    0, ...
%          'SaveKernel',      1), ...
%          'normalize', 'none');  % None: Save non-standardized time-frequency maps
        
     sFiles = bst_process('CallProcess', 'process_timefreq', sFiles_last, [], ...
    'clusters',  {}, ...
    'scoutfunc', 1, ...  % Mean
    'edit',      struct(...
         'Comment',         'Source_Morlet_35-45Hz', ...
         'TimeBands',       [], ...
         'Freqs',           [35, 35.2, 35.4, 35.6, 35.8, 36, 36.2, 36.4, 36.6, 36.8, 37, 37.2, 37.4, 37.6, 37.8, 38, 38.2, 38.4, 38.6, 38.8, 39, 39.2, 39.4, 39.6, 39.8, 40, 40.2, 40.4, 40.6, 40.8, 41, 41.2, 41.4, 41.6, 41.8, 42, 42.2, 42.4, 42.6, 42.8, 43, 43.2, 43.4, 43.6, 43.8, 44, 44.2, 44.4, 44.6, 44.8, 45], ...
         'MorletFc',        40, ...
         'MorletFwhmTc',    2, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'magnitude', ...
         'Output',          'average', ...
         'RemoveEvoked',    0, ...
         'SaveKernel',      0), ...
    'normalize', 'none');  % None: Save non-standardized time-frequency maps
     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        clear sFiles_last sFiles_TF Common_operator_file sFiles_new sFiles trial_names sFiles_backup
    end
end
