% Script generated by Brainstorm (01-Aug-2017)

% Input files
sFiles = {...
    'MAP001/MAP001_ArcaraMapping_20171011_04/timefreq_hilbert_171012_1156.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Add tag: Post-Pre_SHAM
sFiles = bst_process('CallProcess', 'process_add_tag', sFiles, [], ...
    'tag',    'Post-Pre_SHAM', ...
    'output', 1);  % Add to comment

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

